### ISSUE TITLE
[Đã hoàn thành] Thiết kế giao diện

### ISSUE THREAD

**Issue by dangfsix** [dangfsix/FrontendProject#2]
### Công việc
Thiết kế giao diện cho các trang sau đây của đồ án:

0. Nguyên mẫu (Prototype)
1. Trang chủ (Home)
2. Trang thể loại (Category)
3. Trang sản phẩm (Product)
4. Trang giỏ hàng (Cart)
5. Trang tài khoản (User)
6. Trang đơn hàng (Orders)
7. Trang đăng nhập (Sign in)
8. Trang đăng ký (Sign up)

### Yêu cầu

- Sử dụng Adobe XD để thiết kế
- Lưu các tệp thiết kế vào thư mục **/design**

### Thời gian hoàn thành: 25/05/2021

**Comment by pthdang** [comment]
Gia hạn đến Thứ 7, 29/5/2021.
