### ISSUE TITLE
[Đã hoàn thành] Tạo tệp dữ liệu mẫu

### ISSUE THREAD

**Issue by dangfsix** [dangfsix/FrontendProject#3]
### Công việc
Tạo các tệp dữ liệu dưới dạng JSON.
### Yêu cầu

- Cần thảo luận nhóm để thống nhất cấu trúc tệp dữ liệu
- Dữ liệu được lưu dưới dạng JSON và các tệp này được lưu trong thư mục **/data**
- Các tệp hình ảnh được lưu trong thư mục **/img** và thể hiện trong tệp dữ liệu dưới dạng đường dẫn tệp (Cần thảo luận thêm)
- Dữ liệu cần sạch sẽ, không lẫn các mã gây nhiễu, lỗi.

### Thời gian hoàn thành: 25/05/2021

**Comment by congthang12312** [comment]
[
 {
   "id": 1,
   "name": "Chảo chiên Tefal Ultimate 20cm ",
   "price": 929000,
   "amount": 5,
   "category": "Bộ nồi và chảo",
   "trademark": "Tefal",
   "origin": "Pháp",
   "description": " Bên ngoài được phủ sơn chống dính và dễ dàng làm sạch",
   "img": [
      "/data/img/1.png",
      "/data/img/2.png",
      "/data/img/3.png"
   ]
},
 {
   "id": 2,
   "name": "Nồi chiên không dầu EY401D15",
   "price": 3099000,
   "amount": 10,
   "category": "Nồi chiên",
   "trademark": "Tefal",
   "origin": "Pháp",
   "description": " Bên ngoài được phủ sơn chống dính và dễ dàng làm sạch",
   "img": [
      "./data/img/4.png",
      "./data/img/5.png",
      "./data/img/6.png"
   ]
}
]
Đây là dạng json danh sách sản phẩm. Mỗi sản phẩm bao gồm: id, tên sản phẩm, giá, số lượng, danh mục, thương hiệu,  xuất xứ,  mô tả, 3 file img.
@pthdang  @NguyenVanQuyetIT  check giùm mình xem định dạng json này ok chưa á.

**Comment by pthdang** [comment]
@congthang12312 Một số góp ý:

1. `"name": "Chảo chiên Tefal Ultimate 20cm ",` → cần trim string để mất dấu cách thừa
2. `"description": " Bên ngoài được phủ sơn chống dính và dễ dàng làm sạch",` → cần trim string, và nội dung quá ngắn so với thực tế. Nếu có xuống dòng thì thế nào?
3. `"/data/img/1.png",` → nên đặt tên theo 1a, 1b, 1c để tương ứng với id của sản phẩm. Cần đặt hình vào thư mục `/img`, không phải `/data/img`.
4. Cần lấy một trang sản phẩm thực tế, rồi chuyển dữ liệu sang dạng JSON tương ứng. Dữ liệu mẫu phía trên còn có vẻ thiếu một số thuộc tính và chưa thực tế.
5. Cần tham khảo thiết kế CSDL của một shopping app, ví dụ: 
- https://mysql.tutorials24x7.com/blog/guide-to-design-database-for-shopping-cart-in-mysql 
- https://i.pinimg.com/originals/05/e0/27/05e02702b477e3e8987c47f5709270bc.png
- ...
để thiết lập các file JSON cho các table khác. Ví dụ: ngoài Product như trên, còn có thể có User (chỉ cần 1 user mẫu là được), Category (và trung gian Product_Category), Tag (Product_Tag), Cart, Rating, Comment, Transaction... tưởng tượng như 1 user đang tương tác với app.

Xem cách sử dụng Markdown trên GitHub: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by NguyenVanQuyetIT** [comment]
Tôi nghĩ mỗi sản phẩm có số lượng thuộc tính không giống nhau, nên chúng ta không nhất thiết phải cố định số lượng các thuộc tính mỗi sản phẩm

**Comment by pthdang** [comment]
Nếu không giá trị cho thuộc tính thì để mặc định là null.

**Comment by congthang12312** [comment]
@NguyenVanQuyetIT  cái này là json mà ông. kiểu như convert từ database sang json á. Cơ mà cái này là cố định.  Không làm việc với database. Tui tham khảo các shop thì các thuộc tính này là cơ bản á.

**Comment by congthang12312** [comment]
@pthdang  đúng rồi. Quan trọng là cái trên cái form. Mai mốt tạo ra sản phẩm á. Còn file data sản phẩm. Còn gì file data gì nữa không?

**Comment by pthdang** [comment]
@congthang12312  Em tự dự đoán, thiết kế và trình bày với nhóm.

**Comment by pthdang** [comment]
@congthang12312 Tình hình sao rồi em? Thắc mắc gì cứ trình bày ở đây.

**Comment by congthang12312** [comment]
Mình mới sửa lại và push lên nhánh thang 2 file gồm các thông tin:
file product: ProductID, ProductName, Price, ProductType, Description, Img1, Img2, Img3
file user: id, username, password, fullname, email, adress, phone
mọi người vô góp ý nhé

**Comment by pthdang** [comment]
@congthang12312 Chưa thấy branch hay pull request nào.

**Comment by pthdang** [comment]
@congthang12312 Góp ý:

- Tệp json được lưu bằng đuôi .json
- Đặt tệp không đúng yêu cầu, cần đặt trong thư mục **/data**

```json
[
 {
   "ProductID": 1,
   "ProductName": "Chảo chiên Tefal Ultimate 20cm ",
   "Price": 929000,
   "ProductType": "Bộ nồi và chảo",
   "Description": " Bên ngoài được phủ sơn chống dính và dễ dàng làm sạch",
   "Img1": "/data/img/1a.png",
   "Img2": "/data/img/1b.png",
   "Img3": "/data/img/1b.png"
 }
]
```
→ vẫn chưa trim ProductName, dư dấu cách cuối cùng.
→ các "Img1", "Img2", "Img3" cần gộp thành 1 mảng hơn là để riêng lẻ.

```json
 {
   "id": 1,
   "username": "thang",
   "password": 123,
   "fullname": "Do Cong Thang"
   "email": "181302@st.hcmuaf.edu.vn",
   "adress":"duong 18 - linh trung- tp.thu duc"
   "Phone":"888999458"
 }
```
→ các tên thuộc tính thiếu thống nhất về quy ước đặt tên, cần xem lại cách viết hoa, viết thường.
→ "adress": sai chính tả
→ Product thì tiếng Việt, còn User thì tiếng Việt bỏ dấu? thiếu đồng bộ.

**Comment by congthang12312** [comment]
ok để lát e sửa lại

**Comment by congthang12312** [comment]
em sửa theo yêu cầu rồi nha. Còn img em thấy tạo ra 1 mảng sẽ bất tiện sau này cho việc code cũng như sưu tầm source json sau này nên em cho nó thành 3 trường cho dễ sưu tầm source sau này

**Comment by pthdang** [comment]
@congthang12312  Vẫn còn lỗi.

- user.json, dòng 7: thiếu dấu phẩy nên bị lỗi
- user.json sao không làm thành mảng như product.json (nếu như data có nhiều user)
