### ISSUE TITLE
[Đã hoàn thành] Tìm hiểu khái quát TypeScript và Angular

### ISSUE THREAD

**Issue by dangfsix** [dangfsix/FrontendProject#4]
### Công việc
Tìm hiểu khái quát TypeScript và Angular, trình bày kiến thức cho toàn nhóm.
### Yêu cầu

- Tìm hiểu điểm khác nhau cơ bản giữa JavaScript và TypeScript
- Tìm hiểu những cú pháp và chức năng cơ bản của Angular
- Viết quy trình ngắn gọn xây dựng những ứng dụng đơn giản, như HelloWorld và Todo App.
- Lưu lại toàn bộ kiến thức và quy trình tìm hiểu được trong một file Word tên là **AngularBasic.docx** trong thư mục **/ref**
- Trình bày kiến thức cho toàn nhóm sau khi đã tìm hiểu

### Thời gian hoàn thành: 25/05/2021

**Comment by pthdang** [comment]
@NguyenVanQuyetIT Tình hình, tiến độ thế nào? Nếu cần gia hạn thì có thể cho đến thứ 7, 29/5/2021.

**Comment by NguyenVanQuyetIT** [comment]
@pthdang Em đang tìm hiểu các khái niệm cơ bản của Angular. Còn chuyện gia hạn thì đến ngày 25 mà chưa xong thì cho em xin gia hạn thêm hehe

**Comment by pthdang** [comment]
Gia hạn đến Thứ 7, 29/5/2021 (theo yêu cầu trên Messenger).

**Comment by NguyenVanQuyetIT** [comment]
@pthdang anh cho em hỏi, về quy trình xây dựng ứng dụng đơn giản như ToDo App thì cụ thể là có cần trình bày code ra luôn hay chỉ nêu cách làm thôi anh?

**Comment by pthdang** [comment]
@NguyenVanQuyetIT Có code thì tốt.
